#Usage:
#	To set a specific keyboard do "xkbcomp layout_name.xkb $DISPLAY"
alias mackb="setxkbmap -model macA2450 && xkbcomp $HOME/.config/Linux_Configs/keyboard_layouts/acer_aspire_a515-54G-59A3/ubuntu/macA2450.xkb $DISPLAY"
alias ogkb="setxkbmap -model original && xkbcomp $HOME/.config/Linux_Configs/keyboard_layouts/acer_aspire_a515-54G-59A3/ubuntu/original.xkb $DISPLAY"
alias shut="shutdown now"
alias restart="shutdown now -r"
alias open="xdg-open"
alias battery="cat /sys/class/power_supply/BAT1/capacity"
alias encrypt="gpg -c --no-symkey-cache $1"
alias decrypt="gpg --quiet -d --no-symkey-cache $1"
